src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/classes/BRCDiscountController.cls
public with sharing class BRCDiscountController {

    @AuraEnabled
    public static List<Pricebook2> getAllPricebooks(){
        List<Pricebook2> pricebookList = new List<Pricebook2>();
        pricebookList = [SELECT Id,Name,Start_Date__c,End_Date__c,IsActive FROM Pricebook2];
        return pricebookList;
    }

    @AuraEnabled
    public static void createPb(Pricebook2 pricebook){
        Pricebook2 newPricebook = (Pricebook2) pricebook;
        insert newPricebook;
    }

}